# Install some packages in the Vagrant Box
---
- name: Install packages for testing in Vagrant box
  hosts: vagrant_test
  sudo: yes

  tasks:
  - name: Install mysql server
    apt: pkg=mysql-server state=installed update_cache=true

  tasks:
  -name: Setup a fake typo3.org database
   command: command: mysql -u root t3org -e '{{ item }}'
   

# my.conf